### PR TITLE
Dockerfile: added new libs for Doxygen compilation

### PR DESCRIPTION
**Pull request by satletio1**
Dockerfile: added new libs for Doxygen compilation.

Also changed dockerfile a little bit, so it is based on our first image.
Please check if it is okay or need rework.

(anyway, Doxygen is compiled :))

### CODE REVIEW

**Comment by bburda** [comment]
I am not sure, does current change will work at all.
In https://docs.docker.com/develop/develop-images/multistage-build/#use-multi-stage-builds
you can read that:
`the second FROM instruction starts a new build stage `
and 
`any intermediate artifacts are left behind, and not saved in the final image`

**Comment by bburda** [comment]
You should probably change order of build stages, build the Doxygen from our fork, and then copy the binary to the dev image.

**Comment by satletio1** [comment]
> I am not sure, does current change will work at all.
> In https://docs.docker.com/develop/develop-images/multistage-build/#use-multi-stage-builds
> you can read that:
> `the second FROM instruction starts a new build stage `
> and
> `any intermediate artifacts are left behind, and not saved in the final image`

It was just first shot (let's say - dirty one).
Of course this need to be checked briefly, because there is something bothering me about this stages...


> You should probably change order of build stages, build the Doxygen from our fork, and then copy the binary to the dev image.

That's for sure.
First we've just added Doxygen to Docker.
When Doxygen (uml version) will be compleared, we can continue with further Docker integration.

**Comment by satletio1** [comment]
Sounds like a plan.
I'll check new setup and push the changes here.

**Comment by bburda** [comment]
@satletio1 any update on this?

**Comment by bburda** [comment]
No update for a long time. Closing.

**Pull request closed without merging**
