### PR TITLE
Add the project Roadmap

### PR DESCRIPTION
**Pull request by bburda**
The initial Roadmap of the project.

### CODE REVIEW

**Review by hliberacki — APPROVED** [review]
looks good

**Comment by slci** [comment]
Very nice.
Open question: Maybe we could use PlantUML for the diagram? (https://plantuml.com/mindmap-diagram) The output picture is not as rich, but the source for it is in easily maintainable text format.

**Comment by bburda** [comment]
> Very nice.
> Open question: Maybe we could use PlantUML for the diagram? (https://plantuml.com/mindmap-diagram) The output picture is not as rich, but the source for it is easily maintainable text format.

@slci 
I am open to tools proposition in which I can create the Roadmap. However, I am a little skeptical about the PlantUML usage in this project. It is an excellent tool for simple UML diagrams. However, in this project, where we need to provide traceability between the requirements, design, and implementation, we should use a tool that offers the SysML support. Unfortunately, PlantUML does not have it.

**Comment by slci** [comment]
> > Very nice.
> > Open question: Maybe we could use PlantUML for the diagram? (https://plantuml.com/mindmap-diagram) The output picture is not as rich, but the source for it is easily maintainable text format.
> 
> @slci
> I am open to tools proposition in which I can create the Roadmap. However, I am a little skeptical about the PlantUML usage in this project. It is an excellent tool for simple UML diagrams. However, in this project, where we need to provide traceability between the requirements, design, and implementation, we should use a tool that offers the SysML support. Unfortunately, PlantUML does not have it.

Sure, that makes sense. If SysML needs to be supported, then it's a no-go for PlanUML.

**Review by slci — COMMENTED** [review]
Maybe one question/comment. In the roadmap, the Milestone 5 is quite a heavy topic IMO. I don't know much about implementation of OTA update but UDS/Diagnostics is a huge piece of software.
I'm wondering if this is a good idea to do it for a demo.

**Comment by bburda** [comment]
> Maybe one question/comment. In the roadmap, the Milestone 5 is quite a heavy topic IMO. I don't know much about implementation of OTA update but UDS/Diagnostics is a huge piece of software.
> I'm wondering if this is a good idea to do it for a demo.

Yes I understand your concern but I think that all milestones are tons of work. The milestone 6 is the finished working demo application, but I believe that we can start writing it after Milestone 3 is ready. The OTA is required to provide the correct installation of the Adaptive Application. At the same time, the Diagnostic is also very important for the whole platform. Without OTA and Diagnostic, there is no way to provide a demo with full platform capabilities.

**Review by pz0 — APPROVED** [review]
Looks good.

**Pull request merged**
